[tool.black]
line-length = 120

[tool.flake8]
max-line-length = 120
inline-quotes = "double"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 120

[tool.pytest.ini_options]
addopts = """
    --cov-report=term-missing:skip-covered
    --cov=host
    --show-capture=stdout
    --strict-markers
    -r fE
    -vvv
"""
